# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-10 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210515_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, help_text='simple description', max_length=10000000000, verbose_name='Description'),
        ),
    ]
